/*
 * MIT License
 *
 * Copyright (c) 2024 Czech Technical University in Prague
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cvut.fel.aic.shortestpaths;

public class shortestPathsJNI {
  public final static native void CHDistanceQueryManagerAPI_initializeCH(long jarg1, CHDistanceQueryManagerAPI jarg1_, String jarg2, String jarg3);
  public final static native long CHDistanceQueryManagerAPI_distanceQuery(long jarg1, CHDistanceQueryManagerAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void CHDistanceQueryManagerAPI_clearStructures(long jarg1, CHDistanceQueryManagerAPI jarg1_);
  public final static native long new_CHDistanceQueryManagerAPI();
  public final static native void delete_CHDistanceQueryManagerAPI(long jarg1);
  public final static native void TNRDistanceQueryManagerAPI_initializeTNR(long jarg1, TNRDistanceQueryManagerAPI jarg1_, String jarg2, String jarg3);
  public final static native long TNRDistanceQueryManagerAPI_distanceQuery(long jarg1, TNRDistanceQueryManagerAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void TNRDistanceQueryManagerAPI_clearStructures(long jarg1, TNRDistanceQueryManagerAPI jarg1_);
  public final static native long new_TNRDistanceQueryManagerAPI();
  public final static native void delete_TNRDistanceQueryManagerAPI(long jarg1);
  public final static native void TNRAFDistanceQueryManagerAPI_initializeTNRAF(long jarg1, TNRAFDistanceQueryManagerAPI jarg1_, String jarg2, String jarg3);
  public final static native long TNRAFDistanceQueryManagerAPI_distanceQuery(long jarg1, TNRAFDistanceQueryManagerAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void TNRAFDistanceQueryManagerAPI_clearStructures(long jarg1, TNRAFDistanceQueryManagerAPI jarg1_);
  public final static native long new_TNRAFDistanceQueryManagerAPI();
  public final static native void delete_TNRAFDistanceQueryManagerAPI(long jarg1);
}
