/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cvut.fel.aic.contractionhierarchies;

public class contractionHierarchiesJNI {
  public final static native void DistanceQueryManagerWithMappingAPI_initializeCH(long jarg1, DistanceQueryManagerWithMappingAPI jarg1_, String jarg2, String jarg3);
  public final static native double DistanceQueryManagerWithMappingAPI_distanceQuery(long jarg1, DistanceQueryManagerWithMappingAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void DistanceQueryManagerWithMappingAPI_clearStructures(long jarg1, DistanceQueryManagerWithMappingAPI jarg1_);
  public final static native long new_DistanceQueryManagerWithMappingAPI();
  public final static native void delete_DistanceQueryManagerWithMappingAPI(long jarg1);
  public final static native void DistanceQueryManagerAPI_initializeCH(long jarg1, DistanceQueryManagerAPI jarg1_, String jarg2);
  public final static native double DistanceQueryManagerAPI_distanceQuery(long jarg1, DistanceQueryManagerAPI jarg1_, long jarg2, long jarg3);
  public final static native void DistanceQueryManagerAPI_clearStructures(long jarg1, DistanceQueryManagerAPI jarg1_);
  public final static native long new_DistanceQueryManagerAPI();
  public final static native void delete_DistanceQueryManagerAPI(long jarg1);
}
