/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cvut.fel.aic.contractionhierarchies;

public class DistanceQueryManagerWithMappingAPI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DistanceQueryManagerWithMappingAPI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DistanceQueryManagerWithMappingAPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        contractionHierarchiesJNI.delete_DistanceQueryManagerWithMappingAPI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void initializeCH(String chFile, String mappingFile) {
    contractionHierarchiesJNI.DistanceQueryManagerWithMappingAPI_initializeCH(swigCPtr, this, chFile, mappingFile);
  }

  public double distanceQuery(java.math.BigInteger source, java.math.BigInteger target) {
    return contractionHierarchiesJNI.DistanceQueryManagerWithMappingAPI_distanceQuery(swigCPtr, this, source, target);
  }

  public void clearStructures() {
    contractionHierarchiesJNI.DistanceQueryManagerWithMappingAPI_clearStructures(swigCPtr, this);
  }

  public DistanceQueryManagerWithMappingAPI() {
    this(contractionHierarchiesJNI.new_DistanceQueryManagerWithMappingAPI(), true);
  }

}
