//
// Author: Xenty (Michal Cvach)
// Created on: 02.12.19
//

#ifndef CONTRACTION_HIERARCHIES_TNRAFPATHQUERYMANAGER_H
#define CONTRACTION_HIERARCHIES_TNRAFPATHQUERYMANAGER_H


class TNRAFPathQueryManager {

};


#endif //CONTRACTION_HIERARCHIES_TNRAFPATHQUERYMANAGER_H
