#ifndef CONTRACTION_HIERARCHIES_TNRAFPREPROCESSINGMODE_H
#define CONTRACTION_HIERARCHIES_TNRAFPREPROCESSINGMODE_H

enum class TNRAFPreprocessingMode {
    SLOW,
    DM,
    FAST
};

#endif //CONTRACTION_HIERARCHIES_TNRAFPREPROCESSINGMODE_H 