//
// Author: Xenty (Michal Cvach)
// Created on: 1.8.18
//

#ifndef TRANSIT_NODE_ROUTING_CONTRACTIONHIERARCHY_H
#define TRANSIT_NODE_ROUTING_CONTRACTIONHIERARCHY_H


class ContractionHierarchy {

};


#endif //TRANSIT_NODE_ROUTING_CONTRACTIONHIERARCHY_H
