%module contractionHierarchies
%include IntegerDistanceQueryManagerAPI.i
%include IntegerDistanceQueryManagerWithMappingAPI.i
%include FPointDistanceQueryManagerAPI.i
%include FPointDistanceQueryManagerWithMappingAPI.i
