//
// Author: Xenty (Michal Cvach)
// Created on: 21.03.20
//

#ifndef CONTRACTION_HIERARCHIES_TNRAFDISTANCEQUERYMANAGERAPI_H
#define CONTRACTION_HIERARCHIES_TNRAFDISTANCEQUERYMANAGERAPI_H



class TNRAFDistanceQueryManagerAPI {

};



#endif //CONTRACTION_HIERARCHIES_TNRAFDISTANCEQUERYMANAGERAPI_H
