//
// Author: Xenty (Michal Cvach)
// Created on: 21.03.20
//

#ifndef CONTRACTION_HIERARCHIES_TNRDISTANCEQUERYMANAGERAPI_H
#define CONTRACTION_HIERARCHIES_TNRDISTANCEQUERYMANAGERAPI_H



class TNRDistanceQueryManagerAPI {

};



#endif //CONTRACTION_HIERARCHIES_TNRDISTANCEQUERYMANAGERAPI_H
